import Providers from "@/providers/Providers";
import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

<link rel="icon" sizes="180x180" href="/UpCycle.scg" /> 
const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  weight: ["400", "500", "600", "300", "700"],
});

export const metadata: Metadata = {
  title: "UpCycle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${robotoSlab.className}  antialiased`}>
        <Providers>
          <Toaster richColors position="top-center" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
